### ISSUE TITLE
Implement data field checks

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#166]
Country names should be in this list (with some exceptions, e.g., Reunion): https://en.wikipedia.org/wiki/List_of_alternative_country_names

- [x] Latitude should be within +/- 90 degrees
- [x] Longitude should be within +/-180 degrees
- [x] Elevation should be within -300 and 9000 m
- [x] Country should checked (#202)
- [x] Data availability should be either: `Freely`, `Upon request`, `Not available`, or blank/`None` #204
- Acronyms should not be duplicated (doesn't fit in the current workflow of checking row by row)
- [x] Instruments should be in G, B, D, Ds, IR, UVA, UVB, UV, PAR, SPN1, RSR, RSI, RSP] #232 

For old metadata formatting (prior to merging of columns described in #111)
- Tier should either be 1 or 2
- Instrument types should be in list: [Thermopile, SPN1, RSR, RSI, RSP]
- Components should be in [G, B, D, IR, UVA, UVB, UV, PAR]

This will help ensure consistent naming and act as a pre-review and save reviewing time.

**Comment by kandersolar** [comment]
#143 includes some of these checks (lat, lon, elevation) and is designed in such a way to make it easy to add additional checks

**Comment by IoannisSifnaios** [comment]
I think the options for data availability should be: `Freely`, `Upon request`, and `Not available`.

Leaving it `blank`/`None` just makes it more confusing...
